name = "blackhole-sms-worker"
main = "src/index.js"
compatibility_date = "2026-08-10"
compatibility_flags = ["nodejs_compat"]

[[queues.producers]]
binding = "EVENTS"
queue = "blackhole-communication-events"

[observability]
enabled = true

[observability.logs]
enabled = true
